### ISSUE TITLE
Missing entry-point, although it is configured in the paeckchen.json

### ISSUE THREAD

**Issue by clebert** [KnisterPeter/paeckchen#266]
**Version:** paeckchen-cli@0.4.0

**paeckchen.json:**

``` json
{
  "input": {
    "entryPoint": "dist/index.js",
    "source": "es5"
  },
  "output": {
    "folder": "public/js",
    "file": "app.js",
    "runtime": "browser",
    "sourceMap": true
  },
  "debug": false
}
```

**Command:** `./node_modules/.bin/paeckchen`

**Result:**

```
  cli ERROR Bundeling failed
Error: Missing entry-point
    at createContext (/Users/cleake/Documents/github/hyperlink.one/node_modules/paeckchen-core/dist/src/bundle.js:116:15)
    at /Users/cleake/Documents/github/hyperlink.one/node_modules/paeckchen-core/dist/src/bundle.js:129:23 +0ms
```

**Example setup:** https://github.com/clebert/ts-paeckchen-setup

**Comment by KnisterPeter** [comment]
The entry-point in the config must be named 'entry'.
This is currently a bit inconsistent but its not really a bug. I'll considering to rename this option in the config file for release 0.5.0
